### ISSUE TITLE
Create database diagram

### ISSUE THREAD

**Issue by romadmn** [BookCrossing-SoftServe/Bookcrossing-Back-End#1]

**Comment by MaksymNovitskyi** [comment]
https://dbdiagram.io/d/5e6792d04495b02c3b880bc7

**Comment by VolodymyrKorpal** [comment]
https://dbdiagram.io/d/5e68bfdc4495b02c3b881889 v0.2

**Comment by VitaliyRud2001** [comment]
https://dbdiagram.io/d/5e69f6d54495b02c3b8825bb v0.3
